### ISSUE TITLE
Open on MAC

### ISSUE THREAD

**Issue by gsibert** [TranceGeniK/bybit-tools#13]
Can't get the downloaded MAC app to open, could it be a Catalina issue?

**Comment by TranceGeniK** [comment]
https://github.com/electron/electron/issues/20242

**Comment by gsibert** [comment]
Notarization issue? https://medium.com/cacher-app/getting-your-electron-app-working-on-macos-catalina-10-15-63e53f397da2

**Comment by TranceGeniK** [comment]
Probably, problem is I don't have a mac myself to test it...

**Comment by gsibert** [comment]
Can you make a dmg target file instead of a zip? I can test that.

**Comment by TranceGeniK** [comment]
Dmg can only be built on macOS

https://github.com/electron-userland/electron-builder/issues/811

**Comment by gsibert** [comment]
Haven't compiled anything myself in years, and never on my MAC. However, managed to compile it on my own and it fires right up :)

**Comment by TranceGeniK** [comment]
great :)
can you share the steps here for other having the same issue please ?

**Comment by gsibert** [comment]
I'll put something together. The problem is I'm not sure what was relevant or unnecessary in my process :)  Also, I had xcode and homebrew installed already which likely saved some steps versus starting from scratch.

**Comment by SacreBleuXCVII** [comment]
For anyone having the same problem, all I needed to do was [type the build commands](https://github.com/TranceGeniK/bybit-tools#build-instructions-) after cloning the repo and then if you go to the `dist_electron/mac` folder you'll find a compiled version that works.

**Comment by TranceGeniK** [comment]
**_macOS Install Instructions_**
Download zip in an empty folder
Unzip  with keka (https://www.keka.io/en/)
Ctrl-click on the unzipped app (https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/10.15/mac/10.15)
Enjoy !
