### ISSUE TITLE
Unmatched IP:Request IP

### ISSUE THREAD

**Issue by zentrader1** [TranceGeniK/bybit-tools#14]
Hey mate, 

I have downloaded the new version of the app and ran into the issue of unmatched IP. Went to the previous version and same issue. I've checked my IP address several times along with the input of my api keys. Not sure why this is happening after several months of using your app. Which is awesome!

**Comment by TranceGeniK** [comment]
Hmm I'm not sure...
Please try removing all accounts in bb-tools and recreate a fresh one, then select it in the top bar.
If that fails, erase the conf directory (C:\users\your_name\appdata\roaming\bybit-tools) and start fresh.
