### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by gitroli** [TranceGeniK/bybit-tools#15]
Hi, 
Im not so familiar with npm and nodejs.
Are there more detailed installation instructions?

**Comment by TranceGeniK** [comment]
If you just want to use bb-tools, head to [releases](https://github.com/TranceGeniK/bybit-tools/releases) and download the right version for your OS.
If you want to build it, clone the repo, install nodejs/npm and run the commands in the directory in your terminal.

**Comment by gitroli** [comment]
ok thanks, I got it. 
One more question:
When I add multiple bybit accounts the orders are executed on all accounts?

**Comment by TranceGeniK** [comment]
Each account will have its own orders and position, nothing is shared between accounts

**Comment by gitroli** [comment]
is such a function possible: to execute orders, cancels, stops, etc. on all accounts?

**Comment by TranceGeniK** [comment]
No there isn't, but why would you want to do that ?

**Comment by gitroli** [comment]
My friends and I follow a trader, and it would be great if dont have to the anything, placing orders and so on, just copy.

**Comment by TranceGeniK** [comment]
Ah okay, didn't think of that use case !
I don't intend to implement that soon, but I put it on my todo list for later
