### ISSUE TITLE
USDT contract support

### ISSUE THREAD

**Issue by Ultrabitch** [TranceGeniK/bybit-tools#17]
Are you planning on release an update for USDT contracts when API will be available ?
Can't wait for it !!

**Comment by dctt** [comment]
Any news about this?

**Comment by Samadriae** [comment]
Yes, I'm really interested also!

**Comment by Crypler** [comment]
USDT most welcome! Hope you can add this. I transferred my funds to bybit just to use your tooling.. However it is not working yet. Hope you can add this in the near future! Cheers. Great F-ing tool btw. Thanks for all the hard work!

**Comment by bjimdar** [comment]
I looked into this and the USDT api is completely separate and additional API from the inverse-perpetual api. Not impossible, just a bunch of work. My main question is how to integrate into existing UI of ByBit-Tools. How do we show an open long and short position at the same time.

Anyone have any ideas?

**Comment by TranceGeniK** [comment]
@bjimdar You're right, the API is separate

The open position is [here](https://github.com/TranceGeniK/bybit-tools/blob/master/src/components/Home/OpenPosition/OpenPosition.html#L4), you could add a second element, or make an array of all positions [here](https://github.com/TranceGeniK/bybit-tools/blob/master/src/plugins/bybitApi.js)

This will need some work though...

**Comment by bjimdar** [comment]
Interesting. I've got some time right now, I think I might try a first pass implementation on a fork. I'll send you a pull-request if I get anything working.

**Comment by TranceGeniK** [comment]
@bjimdar nice :) people will be happy here !

Send me a message if you have questions

**Comment by TranceGeniK** [comment]
Implemented in [Bybit Pro](https://bybit-pro.com/)
