### ISSUE TITLE
Entering number into already-filled field reverses digits

### ISSUE THREAD

**Issue by FearlessFly** [TranceGeniK/bybit-tools#2]
If user tabs into a field already containing a number such as Higher Price or the rest, digits subsequent entered digits are reversed.  Example shows digits after tabbing into each field and entering 1234 are reversed

![Capture](https://user-images.githubusercontent.com/55893485/65792794-7b9cd180-e132-11e9-8385-163901011d65.JPG)

**Comment by TranceGeniK** [comment]
I had a look and it's not easily reproductible
It is a [v-text-field](https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/components/VTextField) from vuetify but could find related issues on their repo
Will look again later

**Comment by TranceGeniK** [comment]
Not a lot that I can do on my side, I will update vuetify regularily, maybe they'll fix it
