### ISSUE TITLE
[FEATURE] Multiple take profit targets

### ISSUE THREAD

**Issue by Poilaucul** [TranceGeniK/bybit-tools#22]
Hello,

Would it be possible to add the ability to set multiple take profit targets with a stop limit order when price reaches deepest entry order?

Or new boxes for Take Profit #1, Take Profit #2, Take Profit #N and so forth.
With a "+" button to add Take Profit Boxes.

Regards,

**Comment by TranceGeniK** [comment]
Implemented in [Bybit Pro](https://bybit-pro.com)

![image](https://user-images.githubusercontent.com/1398818/128688164-ad4d1df8-5ddd-4b19-a531-ddcff03ac424.png)
