### ISSUE TITLE
[FEATURE] Match best price or some ticks away feature

### ISSUE THREAD

**Issue by Poilaucul** [TranceGeniK/bybit-tools#23]
Hello,

This would a nice feature, the ability to match the best price in the orderbook at entry like in Deribit

Exemple for a short:
![image](https://user-images.githubusercontent.com/2638123/85345658-525b7700-b4f3-11ea-8a3c-2b1626a2fdca.png)

Regards,

**Comment by TranceGeniK** [comment]
Implemented in [Bybit Pro](https://marketspy.net/bybit-pro-tool/)

![image](https://user-images.githubusercontent.com/1398818/103787096-79b40480-503d-11eb-8e4e-6b4873ee914e.png)
