### ISSUE TITLE
[FEATURE] Chase price feature

### ISSUE THREAD

**Issue by Poilaucul** [TranceGeniK/bybit-tools#28]
Hi,

Would be nice to be able to chase chase price with limit orders.
Exemple: 
Submit buy order (post only)
Price moves up without filling you
Enable "chase mode"
Click buy/long again and the order is amended to (mark price - 1$)

Same principle for sell/short

**Comment by TranceGeniK** [comment]
I implemented a price tracker in the limit tab in [Bybit Pro](https://marketspy.net/bybit-pro-tool/) that will automatically fill the price input at a distance from current price that is configurable, and a cancel button near the buy/sell to be able to be fast

![image](https://user-images.githubusercontent.com/1398818/103787772-53db2f80-503e-11eb-9b98-23430f1aa7f8.png)

**Comment by TranceGeniK** [comment]
and a real automated price chaser is on the way :)

![image](https://user-images.githubusercontent.com/1398818/103788630-5db16280-503f-11eb-8fbc-4e2045b51a75.png)

**Comment by TranceGeniK** [comment]
Implemented in [Bybit Pro](https://bybit-pro.com/)
