### ISSUE TITLE
[FEATURE] Limit take profit instead of stop market order

### ISSUE THREAD

**Issue by Poilaucul** [TranceGeniK/bybit-tools#29]
Hi,

Would be nice to choose limit orders for take profit orders to avoid fees.

**Comment by bjimdar** [comment]
This is a great idea. I've used this in the past to great effect. The maker credit can partially offset the fees incurred during entry. Upvote!

**Comment by TranceGeniK** [comment]
A limit take profit can be placed with the limit tab in the opposite direction of the trade with reduce-only checked. It must be placed manually though.

**Comment by TranceGeniK** [comment]
Implemented in [Bybit Pro](https://bybit-pro.com)
