### ISSUE TITLE
Multiple account handling?

### ISSUE THREAD

**Issue by FearlessFly** [TranceGeniK/bybit-tools#3]
Enhancement request

A way to handle multiple ByBit accounts.  I tried separating installations in multiple directories with mixed success.  Is difficult to keep straight.  A text account name printing in the banner would be helpful too.

![image](https://user-images.githubusercontent.com/55893485/66259962-1fffc300-e786-11e9-9d23-6f69c294bd2e.png)

**Comment by TranceGeniK** [comment]
It's on my todo list ;)

**Comment by FearlessFly** [comment]
Hello,

I use this tool frequently and enjoy it.  Previously I suggested multi-account usage would be a wonderful enhancement and I'm certain that represents a lot of effort to implement.  This suggestion idea  may short-cut that effort considerably.

Rather than implement multi-account internally to the program, provide a command-line option to supply settings via a named (JSON) text file or command-line variables.  Only one new field may be required in the GUI to identify which account is in use or identify an error , all the others could be quoted variables or in a text file.  Through this method, other programs such as batch files could setup to use the tool without much coding effort.

Thanks for the opportunity to suggest enhancements.

FearlessFly

**Comment by TranceGeniK** [comment]
Hi @FearlessFly,
Thanks for the suggestion, actually it would require about the same amount of work than implementing it directly in the app, but I'm really strggling to find time to work on it these days...
I'll update as soon as possible ;)
