### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by dctt** [TranceGeniK/bybit-tools#30]
I use the program quite often and love to see the new pair USDT but I do not see any further progress at the project. I hope the developer only does not have time, nothing more as health/family problems...  Thanks for all.
Cheers

**Comment by TranceGeniK** [comment]
Hi @dctt ,

I took a step back from leveraged trading and don't use bb-tools anymore at the time.
No health or family problems, thanks for asking :) On the contrary, I have some personal home projects I'm taking care of so I don't really have time for this at the moment. I know some features are lacking but I don't think I'll be working on them for some time. This software is open source, so your best bet for now is to find another dev who can code in js and make them implement those :) 

Cheers
