### ISSUE TITLE
XRP/USD Pair Integration 

### ISSUE THREAD

**Issue by dropflipper** [TranceGeniK/bybit-tools#33]
Hey there guys!  Thanks for the great tool and awesome work.  Anyways, I really wish there was an XRP/USD trading feature on this software.  So much so, I'd be willing to pay the creator to add this feature.  Please let me know if it would be worth your time to add this, even as a freelance gig
<img width="1362" alt="XRPpair" src="https://user-images.githubusercontent.com/74263434/98713929-19eef500-233d-11eb-9c9c-4439655175f0.png">
.  Thanks again.

**Comment by bjimdar** [comment]
Hey, so just fyi.. I've been in contact with the developer here and I'm actively working on update to this tool on my fork over at https://github.com/bjimdar/bybit-tools. I'm looking into adding support for the new ByBit trading pairs as well. Let me know what other feature's you're interested in.

**Comment by dropflipper** [comment]
Thats great!  I am really looking forward to the release with working XRP
pair.  I am mainly a trader, and not really a programmer, so I would be
really into getting the working Bybit tools for XRP.   Would I have to
build the release from these files?  Or how can I get the version just like
you have in the screenshot?

**Comment by bjimdar** [comment]
OK, so I just re-read your original post and while I am working on a fork, I should point out that the current version of this app already has support for XRP. 

It only shows up after you connect the API.

![bybit-xrp-support](https://user-images.githubusercontent.com/587483/98734745-40ba2500-2357-11eb-9065-5e41a212bda3.JPG)

Check it out and let me know if it works for you

**Comment by dropflipper** [comment]
Ok, wow.  Thats great!, Thank you for that bro!
