### ISSUE TITLE
bitmex compatibility

### ISSUE THREAD

**Issue by ibuythensell** [TranceGeniK/bybit-tools#5]
hey,

for comfort and the occasional market order discount, i trade on bitmex. i have been looking for sth like this for a while. 
sadly the bitmex API key is 24 letters long, while your tool only allows 18 letters.

will there be a possiblity to add bitmex API in the future? or do you know of any similar tool for bitmex?

regards

**Comment by TranceGeniK** [comment]
This tool is for bybit only at the moment, you can check [BitMEXAssistant](https://github.com/kyapp69/BitMEXAssistant) for bitmex
