### ISSUE TITLE
Unmatched IP error and Sign error 

### ISSUE THREAD

**Issue by jamesponce** [TranceGeniK/bybit-tools#6]
I keep getting an unmatched IP error: request ip: ( my ip address) every second. Also when I try to launch orders it says there is a sign error. I double checked my api key and everything was put in correctly. Please not I am using a vpn but even when I turn the vpn off i get the same error.

**Comment by TranceGeniK** [comment]
There is a request for your current position every second
Your API key should be associated with your *public* IP address in the bybit form. You can get it here : https://www.whatismyip.com/
While rare, sometimes data can be corrupted, please delete the config folder located in C:\Users\username\appdata\roaming\bybit-tools and try again from scratch

**Comment by jamesponce** [comment]
Will definitely try that thanks man. Awesome tool. PS. I downgraded to beta 3.2 and it works for me. I'll try erasing any corrupted data and attempt 4?0 again.
