### ISSUE TITLE
Quantity of active open orders 

### ISSUE THREAD

**Issue by dctt** [TranceGeniK/bybit-tools#8]
It would be nice to see the total quantity of active open orders like  (x shorts / y longs)

You are doing a great job. Keep up the good work.

**Comment by dctt** [comment]
why? not possible?

**Comment by TranceGeniK** [comment]
https://github.com/TranceGeniK/bybit-tools/releases/tag/0.4.2-beta

**Comment by dctt** [comment]
great. I thought it was not possible.  thanks.

**Comment by dctt** [comment]
Ahh. after I check I see you add the number of orders.  But it is something but usefull as the value of the orders.  I mean  like in total openorders:  10000USD short /  5000USD long

**Comment by TranceGeniK** [comment]
oh okay, didn't understand that, I'm reopening, but won't be working on it today though
